version: "3.8"
services:
  postgres:
    image: postgres:16
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: portfolio_db
    ports:
      - "5432:5432"

  redis:
    image: redis:7
    ports:
      - "6379:6379"

  kafka:
    image: bitnami/kafka:3
    environment:
      KAFKA_BROKER_ID: 1
      KAFKA_LISTENERS: PLAINTEXT://:9092
      KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://localhost:9092
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
    ports:
      - "9092:9092"
  gateway:
    build: ./cmd/gateway
    ports:
      - "8080:8080"
    depends_on:
      - postgres
      - kafka
      - redis
    environment:
      DATABASE_URL: postgres://postgres:postgres@postgres:5432/portfolio_db?sslmode=disable
      KAFKA_BROKERS: kafka:9092
      REDIS_ADDR: redis:6379
  zookeeper:
    image: bitnami/zookeeper:3
    ports:
      - "2181:2181"
